=== machina-widmo/5e-database/Schemas/DatabaseSchemas/5e-SRD-Languages.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "Schemas/DatabaseSchemas/5e-SRD-Languages.schema.json",
    "type": "array",
    "items": {
        "title": "LanguageEntry",
        "type": "object",
        "required": [
            "descriptor",
            "type",
            "typical_speakers",
            "script"
        ],
        "properties": {
            "descriptor": {
                "$ref": "Schemas/SupportingSchemas/DatabaseEntryDescriptor.schema.json"
            },
            "type": {
                "type": "string"
            },
            "typical_speakers": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "script": {
                "type": "string"
            }
        }
    }
}

=== machina-widmo/5e-database/5e-SRD-Languages.json
[
    {
        "type": "Standard",
        "typical_speakers": [
            "Humans"
        ],
        "script": "Common",
        "descriptor": {
            "index": 0,
            "url": "/api/languages/0",
            "name": "Common",
            "desc": []
        }
    },
    {
        "type": "Standard",
        "typical_speakers": [
            "Dwarves"
        ],
        "script": "Dwarvish",
        "descriptor": {
            "index": 1,
            "url": "/api/languages/1",
            "name": "Dwarvish",
            "desc": []
        }
    },
    {
        "type": "Standard",
        "typical_speakers": [
            "Elves"
        ],
        "script": "Elvish",
        "descriptor": {
            "index": 2,
            "url": "/api/languages/2",
            "name": "Elvish",
            "desc": []
        }
    },
    {
        "type": "Standard",
        "typical_speakers": [
            "Ogres",
            "Giants"
        ],
        "script": "Dwarvish",
        "descriptor": {
            "index": 3,
            "url": "/api/languages/3",
            "name": "Giant",
            "desc": []
        }
    },
    {
        "type": "Standard",
        "typical_speakers": [
            "Gnomes"
        ],
        "script": "Dwarvish",
        "descriptor": {
            "index": 4,
            "url": "/api/languages/4",
            "name": "Gnomish",
            "desc": []
        }
    },
    {
        "type": "Standard",
        "typical_speakers": [
            "Goblinoids"
        ],
        "script": "Dwarvish",
        "descriptor": {
            "index": 5,
            "url": "/api/languages/5",
            "name": "Goblin",
            "desc": []
        }
    },
    {
        "type": "Standard",
        "typical_speakers": [
            "Halflings"
        ],
        "script": "Common",
        "descriptor": {
            "index": 6,
            "url": "/api/languages/6",
            "name": "Halfling",
            "desc": []
        }
    },
    {
        "type": "Standard",
        "typical_speakers": [
            "Orcs"
        ],
        "script": "Dwarvish",
        "descriptor": {
            "index": 7,
            "url": "/api/languages/7",
            "name": "Orc",
            "desc": []
        }
    },
    {
        "type": "Exotic",
        "typical_speakers": [
            "Demons"
        ],
        "script": "Infernal",
        "descriptor": {
            "index": 8,
            "url": "/api/languages/8",
            "name": "Abyssal",
            "desc": []
        }
    },
    {
        "type": "Exotic",
        "typical_speakers": [
            "Celestials"
        ],
        "script": "Celestial",
        "descriptor": {
            "index": 9,
            "url": "/api/languages/9",
            "name": "Celestial",
            "desc": []
        }
    },
    {
        "type": "Exotic",
        "typical_speakers": [
            "Dragons",
            "Dragonborn"
        ],
        "script": "Draconic",
        "descriptor": {
            "index": 10,
            "url": "/api/languages/10",
            "name": "Draconic",
            "desc": []
        }
    },
    {
        "type": "Exotic",
        "typical_speakers": [
            "Aboleths",
            "Cloakers"
        ],
        "script": "None",
        "descriptor": {
            "index": 11,
            "url": "/api/languages/11",
            "name": "Deep Speech",
            "desc": []
        }
    },
    {
        "type": "Exotic",
        "typical_speakers": [
            "Devils"
        ],
        "script": "Infernal",
        "descriptor": {
            "index": 12,
            "url": "/api/languages/12",
            "name": "Infernal",
            "desc": []
        }
    },
    {
        "type": "Exotic",
        "typical_speakers": [
            "Elementals"
        ],
        "script": "Dwarvish",
        "descriptor": {
            "index": 13,
            "url": "/api/languages/13",
            "name": "Primordial",
            "desc": []
        }
    },
    {
        "type": "Exotic",
        "typical_speakers": [
            "Fey creatures"
        ],
        "script": "Elvish",
        "descriptor": {
            "index": 14,
            "url": "/api/languages/14",
            "name": "Sylvan",
            "desc": []
        }
    },
    {
        "type": "Exotic",
        "typical_speakers": [
            "Underdark traders"
        ],
        "script": "Elvish",
        "descriptor": {
            "index": 15,
            "url": "/api/languages/15",
            "name": "Undercommon",
            "desc": []
        }
    }
]
