=== machina-widmo/5e-database/Schemas/DatabaseSchemas/5e-SRD-StartingEquipment.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "Schemas/DatabaseSchemas/5e-SRD-StartingEquipment.schema.json",
    "type": "array",
    "items": {
        "title": "StartingEquipmentEntry",
        "type": "object",
        "required": [
            "descriptor",
            "class",
            "starting_equipment",
            "choices"
        ],
        "properties": {
            "descriptor": {
                "$ref": "Schemas/SupportingSchemas/DatabaseEntryDescriptor.schema.json"
            },
            "class": {
                "$ref": "Schemas/SupportingSchemas/DatabaseEntryReference.schema.json"
            },
            "starting_equipment": {
                "type": "array",
                "items": {
                    "$ref": "Schemas/SupportingSchemas/InventoryItemDescriptor.schema.json"
                }
            },
            "choices": {
                "type": "array",
                "items": {
                    "type": "array",
                    "items": {
                        "allOf": [
                            { "$ref": "Schemas/SupportingSchemas/ChoicePool.schema.json" },
                            {
                                "properties": {
                                    "from": {
                                        "items": {
                                            "$ref": "Schemas/SupportingSchemas/InventoryItemDescriptor.schema.json"
                                        }
                                    }
                                }
                            }
                        ]
                    }
                }
            }
        }
    }
}

=== machina-widmo/5e-database/5e-SRD-StartingEquipment.json
[
    {
        "class": {
            "url": "/api/classes/0",
            "name": "Barbarian"
        },
        "starting_equipment": [
            {
                "item": {
                    "url": "/api/equipment/157",
                    "name": "Explorer's Pack"
                },
                "quantity": 1
            },
            {
                "item": {
                    "url": "/api/equipment/4",
                    "name": "Javelin"
                },
                "quantity": 4
            }
        ],
        "choices": [
            [
                {
                    "choose": 1,
                    "type": "equipment",
                    "from": [
                        {
                            "item": {
                                "url": "/api/equipment/17",
                                "name": "Greataxe"
                            },
                            "quantity": 1
                        }
                    ]
                },
                {
                    "choose": 1,
                    "type": "equipment",
                    "from": [
                        {
                            "item": {
                                "url": "/api/equipment/14",
                                "name": "Battleaxe"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/15",
                                "name": "Flail"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/16",
                                "name": "Glaive"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/17",
                                "name": "Greataxe"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/18",
                                "name": "Greatsword"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/19",
                                "name": "Halberd"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/20",
                                "name": "Lance"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/21",
                                "name": "Longsword"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/22",
                                "name": "Maul"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/23",
                                "name": "Morningstar"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/24",
                                "name": "Pike"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/25",
                                "name": "Rapier"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/26",
                                "name": "Scimitar"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/27",
                                "name": "Shortsword"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/28",
                                "name": "Trident"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/29",
                                "name": "War pick"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/30",
                                "name": "Warhammer"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/31",
                                "name": "Whip"
                            },
                            "quantity": 1
                        }
                    ]
                }
            ],
            [
                {
                    "choose": 1,
                    "type": "equipment",
                    "from": [
                        {
                            "item": {
                                "url": "/api/equipment/3",
                                "name": "Handaxe"
                            },
                            "quantity": 2
                        }
                    ]
                },
                {
                    "choose": 1,
                    "type": "equipment",
                    "from": [
                        {
                            "item": {
                                "url": "/api/equipment/0",
                                "name": "Club"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/1",
                                "name": "Dagger"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/2",
                                "name": "Greatclub"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/3",
                                "name": "Handaxe"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/4",
                                "name": "Javelin"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/5",
                                "name": "Light hammer"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/6",
                                "name": "Mace"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/7",
                                "name": "Quarterstaff"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/8",
                                "name": "Sickle"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/9",
                                "name": "Spear"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/10",
                                "name": "Crossbow, light"
                            },
                            "quantity": 1
                        },
                        {
                            "item": {
                                "url": "/api/equipment/11",
                                "name": "Dart"
                            },
                            "quantity": 1
                        },
